(() => {
  const $ = id => document.getElementById(id);
  const menuScreen = $('menuScreen'), howScreen = $('howScreen'), gameScreen = $('gameScreen');
  const canvas = $('gameCanvas'), ctx = canvas.getContext('2d');
  const healthFill = $('healthFill'), healthText = $('healthText'), dashFill = $('dashFill'), dashText = $('dashText');
  let W=0,H=0,dpr=1, raf=0, last=0, running=false, paused=false, ended=false, soundOn=true, audioCtx=null;
  let player, bullets=[], enemies=[], particles=[], pickups=[], stars=[], score=0,kills=0,wave=1,spawnLeft=0,spawnTimer=0,waveDelay=0,shake=0,mouse={x:0,y:0,down:false},keys={},time=0,dashCooldown=0,fireCooldown=0,boss=null;
  const rand=(a,b)=>Math.random()*(b-a)+a, clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
  function resize(){const r=canvas.getBoundingClientRect();dpr=Math.min(window.devicePixelRatio||1,2);W=Math.max(1,r.width);H=Math.max(1,r.height);canvas.width=Math.floor(W*dpr);canvas.height=Math.floor(H*dpr);ctx.setTransform(dpr,0,0,dpr,0,0);if(!mouse.x){mouse.x=W/2;mouse.y=H/2;}stars=Array.from({length:Math.floor(W*H/6500)},()=>({x:Math.random()*W,y:Math.random()*H,z:rand(.25,1),p:rand(0,6)}));}
  window.addEventListener('resize',resize); resize();
  function tone(freq=440,dur=.06,type='sine',vol=.025){if(!soundOn)return;try{audioCtx=audioCtx||new(window.AudioContext||window.webkitAudioContext)();const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type=type;o.frequency.value=freq;g.gain.setValueAtTime(vol,audioCtx.currentTime);g.gain.exponentialRampToValueAtTime(.001,audioCtx.currentTime+dur);o.connect(g);g.connect(audioCtx.destination);o.start();o.stop(audioCtx.currentTime+dur);}catch(e){}}
  function showMenu(){running=false;paused=false;ended=false;gameScreen.classList.add('hidden');howScreen.classList.add('hidden');menuScreen.classList.remove('hidden');if(raf)cancelAnimationFrame(raf);}
  function startGame(){menuScreen.classList.add('hidden');howScreen.classList.add('hidden');gameScreen.classList.remove('hidden');resize();resetGame();running=true;paused=false;ended=false;last=performance.now();raf=requestAnimationFrame(loop);}
  function resetGame(){player={x:W/2,y:H/2,r:12,hp:100,maxHp:100,speed:245,inv:0,dash:0,aim:0};bullets=[];enemies=[];particles=[];pickups=[];score=0;kills=0;wave=1;spawnLeft=0;spawnTimer=.7;waveDelay=1.5;shake=0;time=0;dashCooldown=0;fireCooldown=0;boss=null;updateHud();$('waveText').textContent='01';$('waveState').textContent='BREACH INCOMING';$('objectiveText').textContent='ELIMINATE ALL HOSTILES';$('pauseOverlay').classList.add('hidden');$('gameOverOverlay').classList.add('hidden');}
  function beginWave(){spawnLeft=7+wave*3;spawnTimer=.3;waveDelay=0;$('waveText').textContent=String(wave).padStart(2,'0');$('waveState').textContent=wave%5===0?'ELITE SIGNATURE':'HOSTILES DETECTED';$('objectiveText').textContent=wave%5===0?'ELIMINATE THE ELITE':'ELIMINATE ALL HOSTILES';if(wave%5===0){spawnLeft=0;spawnBoss();}tone(240,.2,'sawtooth',.04);}
  function spawnBoss(){const e={x:W/2,y:-55,r:35,hp:240+wave*22,maxHp:240+wave*22,speed:48,kind:'boss',shoot:1.2,phase:0};enemies.push(e);boss=e;for(let i=0;i<25;i++)burst(e.x,e.y,'#a56cff',2.5);}
  function spawnEnemy(){const edge=Math.floor(Math.random()*4);let x=edge===0?rand(0,W):edge===1?W+20:edge===2?rand(0,W):-20;let y=edge===0?-20:edge===1?rand(0,H):edge===2?H+20:rand(0,H);const roll=Math.random();let kind=roll<.18?'shooter':roll<.34?'tank':'drone';if(wave%5===0&&Math.random()<.5)kind='drone';let r=kind==='tank'?18:kind==='shooter'?13:10;enemies.push({x,y,r,hp:kind==='tank'?4:kind==='shooter'?2:1,maxHp:kind==='tank'?4:kind==='shooter'?2:1,speed:(kind==='tank'?48:kind==='shooter'?66:95)+wave*3,kind,shoot:rand(.7,2.2),phase:rand(0,6)});}
  function burst(x,y,color,n=8){for(let i=0;i<n;i++){const a=rand(0,Math.PI*2),s=rand(30,230);particles.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s,life:rand(.2,.65),max:.65,size:rand(1,3),color});}}
  function shoot(){if(fireCooldown>0)return;fireCooldown=.13;const a=player.aim;bullets.push({x:player.x+Math.cos(a)*17,y:player.y+Math.sin(a)*17,vx:Math.cos(a)*650,vy:Math.sin(a)*650,r:3.2,life:.9,damage:1});tone(rand(460,620),.045,'triangle',.018);for(let i=0;i<2;i++)particles.push({x:player.x+Math.cos(a)*18,y:player.y+Math.sin(a)*18,vx:rand(-35,35)+Math.cos(a)*rand(15,60),vy:rand(-35,35)+Math.sin(a)*rand(15,60),life:.13,max:.13,size:2,color:'#54f6f1'});}
  function enemyShoot(e){const a=Math.atan2(player.y-e.y,player.x-e.x);bullets.push({x:e.x,y:e.y,vx:Math.cos(a)*230,vy:Math.sin(a)*230,r:4,life:4,enemy:true});tone(160,.05,'square',.008);}
  function dash(){if(dashCooldown>0||player.dash>0)return;let dx=(keys.d?1:0)-(keys.a?1:0),dy=(keys.s?1:0)-(keys.w?1:0);if(!dx&&!dy){dx=Math.cos(player.aim);dy=Math.sin(player.aim);}const l=Math.hypot(dx,dy)||1;player.dash=.19;player.inv=.42;dashCooldown=2.6;player.dashVx=dx/l*900;player.dashVy=dy/l*900;for(let i=0;i<12;i++)burst(player.x,player.y,'#a56cff',1);tone(700,.12,'sawtooth',.03);}
  function update(dt){time+=dt;fireCooldown=Math.max(0,fireCooldown-dt);dashCooldown=Math.max(0,dashCooldown-dt);player.inv=Math.max(0,player.inv-dt);if(player.dash>0){player.dash-=dt;player.x+=player.dashVx*dt;player.y+=player.dashVy*dt;}else{let dx=((keys.d||keys.arrowright)?1:0)-((keys.a||keys.arrowleft)?1:0),dy=((keys.s||keys.arrowdown)?1:0)-((keys.w||keys.arrowup)?1:0),l=Math.hypot(dx,dy)||1;if(dx||dy){player.x+=dx/l*player.speed*dt;player.y+=dy/l*player.speed*dt;}}player.x=clamp(player.x,player.r+3,W-player.r-3);player.y=clamp(player.y,player.r+3,H-player.r-3);player.aim=Math.atan2(mouse.y-player.y,mouse.x-player.x);if(mouse.down||keys[' '])shoot();
    if(waveDelay>0){waveDelay-=dt;if(waveDelay<=0)beginWave();}
    if(spawnLeft>0){spawnTimer-=dt;if(spawnTimer<=0){spawnEnemy();spawnLeft--;spawnTimer=Math.max(.22,.78-wave*.018);}}
    if(spawnLeft===0&&enemies.length===0&&waveDelay<=0){waveDelay=2.3;wave++;$('waveState').textContent='SECTOR CLEAR';$('objectiveText').textContent='NEXT BREACH INCOMING';score+=250+wave*20;tone(600,.18,'sine',.04);}
    for(let i=bullets.length-1;i>=0;i--){const b=bullets[i];b.x+=b.vx*dt;b.y+=b.vy*dt;b.life-=dt;if(b.life<=0||b.x<-30||b.x>W+30||b.y<-30||b.y>H+30){bullets.splice(i,1);continue;}if(!b.enemy){let hit=false;for(let j=enemies.length-1;j>=0;j--){const e=enemies[j];if(Math.hypot(b.x-e.x,b.y-e.y)<e.r+b.r){e.hp-=b.damage;burst(b.x,b.y,e.kind==='boss'?'#a56cff':'#54f6f1',3);bullets.splice(i,1);hit=true;if(e.hp<=0){score+=e.kind==='boss'?1500:e.kind==='tank'?150: e.kind==='shooter'?100:75;kills++;if(e.kind==='boss')boss=null;burst(e.x,e.y,e.kind==='boss'?'#a56cff':'#ff557e',e.kind==='boss'?42:12);if(Math.random()<.22||e.kind==='boss')pickups.push({x:e.x,y:e.y,r:7,life:10});enemies.splice(j,1);tone(e.kind==='boss'?90:220,.09,'sawtooth',.025);}break;}}}}
    for(const e of enemies){const a=Math.atan2(player.y-e.y,player.x-e.x),dist=Math.hypot(player.x-e.x,player.y-e.y);e.phase+=dt;if(e.kind==='boss'){if(e.y<100)e.y+=e.speed*dt;else{e.x+=Math.sin(time*.7)*e.speed*dt*1.5;e.y+=Math.sin(time*1.3)*12*dt;}e.shoot-=dt;if(e.shoot<=0){e.shoot=.9;for(let k=0;k<8;k++){const ang=time*.6+k*Math.PI/4;bullets.push({x:e.x,y:e.y,vx:Math.cos(ang)*150,vy:Math.sin(ang)*150,r:5,life:5,enemy:true});}}}else if(e.kind==='shooter'){if(dist>250){e.x+=Math.cos(a)*e.speed*dt;e.y+=Math.sin(a)*e.speed*dt;}else if(dist<170){e.x-=Math.cos(a)*e.speed*.6*dt;e.y-=Math.sin(a)*e.speed*.6*dt;}e.shoot-=dt;if(e.shoot<=0){e.shoot=rand(1.2,2);enemyShoot(e);}}else{e.x+=Math.cos(a)*e.speed*dt;e.y+=Math.sin(a)*e.speed*dt;if(e.kind==='drone'){e.x+=Math.sin(e.phase*2)*20*dt;e.y+=Math.cos(e.phase*2)*20*dt;}}if(dist<e.r+player.r&&player.inv<=0){player.hp-=e.kind==='boss'?18: e.kind==='tank'?20:12;player.inv=.65;shake=10;burst(player.x,player.y,'#ff557e',14);tone(85,.18,'sawtooth',.05);if(e.kind!=='boss'&&e.kind!=='tank'){e.hp=0;}}}
    for(let i=enemies.length-1;i>=0;i--)if(enemies[i].hp<=0){const e=enemies[i];if(e.kind==='boss')boss=null;enemies.splice(i,1);}
    for(let i=bullets.length-1;i>=0;i--){const b=bullets[i];if(b.enemy&&Math.hypot(b.x-player.x,b.y-player.y)<b.r+player.r&&player.inv<=0){bullets.splice(i,1);player.hp-=9;player.inv=.55;shake=7;burst(player.x,player.y,'#ff557e',10);tone(100,.1,'square',.03);}}
    for(let i=pickups.length-1;i>=0;i--){const p=pickups[i];p.life-=dt;if(Math.hypot(p.x-player.x,p.y-player.y)<p.r+player.r+6){player.hp=Math.min(100,player.hp+15);score+=50;burst(p.x,p.y,'#54f6f1',12);pickups.splice(i,1);tone(800,.12,'sine',.03);}else if(p.life<=0)pickups.splice(i,1);}
    for(let i=particles.length-1;i>=0;i--){const p=particles[i];p.x+=p.vx*dt;p.y+=p.vy*dt;p.vx*=Math.pow(.08,dt);p.vy*=Math.pow(.08,dt);p.life-=dt;if(p.life<=0)particles.splice(i,1);}
    if(shake>0)shake=Math.max(0,shake-dt*30);updateHud();if(player.hp<=0)gameOver();}
  function updateHud(){healthFill.style.width=clamp(player.hp,0,100)+'%';healthFill.style.background=player.hp<30?'var(--red)':'var(--cyan)';healthText.textContent=Math.ceil(clamp(player.hp,0,100))+'%';dashFill.style.width=((2.6-dashCooldown)/2.6*100)+'%';dashText.textContent=dashCooldown<=0?'READY [SPACE]':'RECHARGING';$('scoreText').textContent=String(score).padStart(6,'0');$('killText').textContent=kills;}
  function draw(){ctx.save();if(shake)ctx.translate(rand(-shake,shake),rand(-shake,shake));ctx.clearRect(-20,-20,W+40,H+40);ctx.fillStyle='#070b18';ctx.fillRect(-20,-20,W+40,H+40);
    const bg=ctx.createRadialGradient(W*.5,H*.48,20,W*.5,H*.48,Math.max(W,H)*.7);bg.addColorStop(0,'#101a35');bg.addColorStop(1,'#050813');ctx.fillStyle=bg;ctx.fillRect(0,0,W,H);
    for(const s of stars){s.p+=.012;ctx.globalAlpha=.2+s.z*.55;ctx.fillStyle=s.z>.8?'#b8ffff':'#839bce';ctx.fillRect(s.x+Math.sin(s.p)*4,s.y,1+s.z,1+s.z);}ctx.globalAlpha=1;
    ctx.strokeStyle='rgba(87,130,210,.075)';ctx.lineWidth=1;const grid=48,ox=(time*7)%grid,oy=(time*4)%grid;for(let x=-grid+ox;x<W+grid;x+=grid){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,H);ctx.stroke();}for(let y=-grid+oy;y<H+grid;y+=grid){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(W,y);ctx.stroke();}
    // faint sector rings
    ctx.strokeStyle='rgba(84,246,241,.06)';for(let i=1;i<5;i++){ctx.beginPath();ctx.arc(W/2,H/2,i*Math.min(W,H)/8,0,Math.PI*2);ctx.stroke();}
    for(const p of pickups){ctx.save();ctx.translate(p.x,p.y);ctx.rotate(time*2);ctx.shadowBlur=18;ctx.shadowColor='#54f6f1';ctx.strokeStyle='#54f6f1';ctx.lineWidth=2;ctx.strokeRect(-p.r,-p.r,p.r*2,p.r*2);ctx.beginPath();ctx.moveTo(-p.r+2,0);ctx.lineTo(p.r-2,0);ctx.moveTo(0,-p.r+2);ctx.lineTo(0,p.r-2);ctx.stroke();ctx.restore();}
    for(const b of bullets){ctx.beginPath();ctx.shadowBlur=b.enemy?12:18;ctx.shadowColor=b.enemy?'#ff557e':'#54f6f1';ctx.fillStyle=b.enemy?'#ff668a':'#d7ffff';ctx.arc(b.x,b.y,b.r,0,Math.PI*2);ctx.fill();if(!b.enemy){ctx.strokeStyle='#54f6f1';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(b.x-b.vx*.025,b.y-b.vy*.025);ctx.lineTo(b.x,b.y);ctx.stroke();}}
    for(const e of enemies){ctx.save();ctx.translate(e.x,e.y);const a=Math.atan2(player.y-e.y,player.x-e.x);ctx.rotate(a);const col=e.kind==='boss'?'#b77aff':e.kind==='tank'?'#ff557e':e.kind==='shooter'?'#ffb45c':'#ff5f87';ctx.shadowBlur=e.kind==='boss'?26:14;ctx.shadowColor=col;ctx.strokeStyle=col;ctx.fillStyle=e.kind==='boss'?'#301d50':'#201426';ctx.lineWidth=e.kind==='boss'?3:2;ctx.beginPath();if(e.kind==='boss'){ctx.moveTo(e.r,0);ctx.lineTo(e.r*.4,e.r*.7);ctx.lineTo(-e.r*.6,e.r*.8);ctx.lineTo(-e.r,0);ctx.lineTo(-e.r*.6,-e.r*.8);ctx.lineTo(e.r*.4,-e.r*.7);ctx.closePath();}else if(e.kind==='tank'){ctx.rect(-e.r,-e.r,e.r*2,e.r*2);}else{ctx.moveTo(e.r,0);ctx.lineTo(-e.r*.7,e.r*.8);ctx.lineTo(-e.r*.35,0);ctx.lineTo(-e.r*.7,-e.r*.8);ctx.closePath();}ctx.fill();ctx.stroke();ctx.fillStyle=col;ctx.beginPath();ctx.arc(0,0,e.kind==='boss'?6:3,0,Math.PI*2);ctx.fill();ctx.restore();if(e.hp<e.maxHp||e.kind==='boss'){const bw=e.kind==='boss'?90:28;ctx.fillStyle='#211a32';ctx.fillRect(e.x-bw/2,e.y-e.r-10,bw,3);ctx.fillStyle=col;ctx.fillRect(e.x-bw/2,e.y-e.r-10,bw*clamp(e.hp/e.maxHp,0,1),3);}}
    // player glow and angular fighter
    ctx.save();ctx.translate(player.x,player.y);ctx.rotate(player.aim);if(player.inv>0&&Math.floor(time*25)%2===0)ctx.globalAlpha=.45;ctx.shadowBlur=player.dash>0?35:22;ctx.shadowColor=player.dash>0?'#a56cff':'#54f6f1';ctx.fillStyle='#d9ffff';ctx.strokeStyle='#54f6f1';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(17,0);ctx.lineTo(3,8);ctx.lineTo(-10,12);ctx.lineTo(-6,2);ctx.lineTo(-10,-12);ctx.lineTo(3,-8);ctx.closePath();ctx.fill();ctx.stroke();ctx.fillStyle='#54f6f1';ctx.beginPath();ctx.moveTo(-8,-4);ctx.lineTo(-17,0);ctx.lineTo(-8,4);ctx.closePath();ctx.fill();ctx.restore();
    for(const p of particles){ctx.globalAlpha=clamp(p.life/p.max,0,1);ctx.fillStyle=p.color;ctx.shadowBlur=10;ctx.shadowColor=p.color;ctx.fillRect(p.x,p.y,p.size,p.size);}ctx.globalAlpha=1;ctx.shadowBlur=0;
    if(boss){ctx.fillStyle='#10162b';ctx.fillRect(W/2-130,22,260,5);ctx.fillStyle='#a56cff';ctx.fillRect(W/2-130,22,260*clamp(boss.hp/boss.maxHp,0,1),5);ctx.fillStyle='#b8a1ff';ctx.font='10px Orbitron';ctx.textAlign='center';ctx.fillText('ELITE SIGNATURE',W/2,16);}
    ctx.restore();}
  function loop(now){if(!running)return;raf=requestAnimationFrame(loop);if(paused)return;const dt=Math.min((now-last)/1000,.033);last=now;update(dt);draw();}
  function gameOver(){if(ended)return;ended=true;running=false;$('finalScore').textContent=String(score).padStart(6,'0');$('finalWave').textContent=String(Math.max(1,wave-1)).padStart(2,'0');$('finalKills').textContent=kills;$('finalMessage').textContent=score>5000?'An extraordinary run, pilot. The void will remember your name.':'The Vanguard has fallen, but the signal remains.';$('gameOverOverlay').classList.remove('hidden');tone(65,.5,'sawtooth',.05);}
  function togglePause(){if(!running||ended)return;paused=!paused;$('pauseOverlay').classList.toggle('hidden',!paused);if(!paused)last=performance.now();}
  $('startBtn').addEventListener('click',startGame);$('briefStart').addEventListener('click',startGame);$('howBtn').addEventListener('click',()=>howScreen.classList.remove('hidden'));$('closeHow').addEventListener('click',()=>howScreen.classList.add('hidden'));$('pauseBtn').addEventListener('click',togglePause);$('resumeBtn').addEventListener('click',togglePause);$('restartBtn').addEventListener('click',startGame);$('playAgainBtn').addEventListener('click',startGame);$('menuBtn').addEventListener('click',showMenu);$('soundBtn').addEventListener('click',()=>{soundOn=!soundOn;$('soundBtn').innerHTML=(soundOn?'♫':'♪')+' <span>'+(soundOn?'SOUND':'MUTED')+'</span>';if(soundOn)tone(500,.08);});
  window.addEventListener('keydown',e=>{const k=e.key.toLowerCase();keys[k]=true;if([' ','arrowup','arrowdown','arrowleft','arrowright'].includes(k))e.preventDefault();if(k===' '&&running&&!paused)dash();if(k==='p'||k==='escape')togglePause();});window.addEventListener('keyup',e=>{keys[e.key.toLowerCase()]=false;});
  canvas.addEventListener('mousemove',e=>{const r=canvas.getBoundingClientRect();mouse.x=e.clientX-r.left;mouse.y=e.clientY-r.top;});canvas.addEventListener('mousedown',e=>{if(e.button===0)mouse.down=true;});window.addEventListener('mouseup',()=>mouse.down=false);canvas.addEventListener('touchmove',e=>{const t=e.touches[0],r=canvas.getBoundingClientRect();mouse.x=t.clientX-r.left;mouse.y=t.clientY-r.top;},{passive:true});canvas.addEventListener('touchstart',e=>{const t=e.touches[0],r=canvas.getBoundingClientRect();mouse.x=t.clientX-r.left;mouse.y=t.clientY-r.top;mouse.down=true;},{passive:true});window.addEventListener('touchend',()=>mouse.down=false);
  // Menu ambience uses the same renderer background language without starting a mission.
  function menuAmbient(){if(!menuScreen.classList.contains('hidden')){const v=document.querySelector('.hero-visual');if(v)v.style.setProperty('--ambient-time',Date.now()%10000+'ms');}requestAnimationFrame(menuAmbient);}menuAmbient();
})();